[server]
address = "127.0.0.1"
maxUploadSize = 20
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#176d56"
backgroundColor = "#f8faf9"
secondaryBackgroundColor = "#edf2ef"
textColor = "#202824"
font = "sans serif"
